---
title: Maker's Asylum
timezone: Asia/Kolkata
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
gems:
- jekyll-seo-tag
- jekyll-sitemap
exclude:
- gulpfile.js
- Gemfile
- Gemfile.lock
- package.json
- README*
- node_modules
- ".gitignore"
