---
title: Maker's Asylum
timezone: Asia/Kolkata
collections:
  labs:
    title: Labs
    output: true
  members:
    title: Members
    output: true
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: members
  values:
    profile picture:
- scope:
    path: ''
    type: projects
  values:
    pictures: []
    members:
- scope:
    path: ''
    type: labs
  values:
    image:
    free hours:
    extra time price:
    powered by:
permalink: pretty
logo: "/uploads/logo.svg"
gems:
- jekyll-seo-tag
- jekyll-sitemap
sass:
  sass_dir: styles/
